apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  annotations:
    # Need to install an earlier version of kubernetes on workstation to use this annotation
    # kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - <REPLACE_ME>
    secretName: tls-secret
  rules:
  - host: <REPLACE_ME>
    http:
      paths:
      - backend:
          serviceName: aks-helloworld
          servicePort: 80
        path: /(.*)
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
# spec:
#   controller: ingress-nginx-controller
#   parameters:
#     apiGroup: k8s.example.com
#     kind: IngressParameters
#     name: external-lb