apiVersion: cert-manager.io/v1alpha2
# An Issuer is a custom resource definition (CRD) made available through the cert-manager controller
# Issuers represent CAs and allow us to automate the generation of certificates
kind: Issuer
metadata:
  name: letsencrypt
spec:
# The Automatic Certificate Management Environment (ACME) protocol automates certificate provisioning
# ACME is the underlying protocol of LetsEncypt CA
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # Temporary email generated via Temp Mail
    email: nafifi3179@j24blog.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux